/**
 * Central SEO primitives — single source of truth for canonical URLs,
 * structured data, and the route registry used by the sitemap.
 */

export const SITE = {
  url: "https://solyio.com",
  name: "Solyio",
  tagline: "Web, Mobile, Cloud & AI Solutions",
  description:
    "Solyio builds web platforms, mobile apps, cloud infrastructure, and AI automation that simplify your business and accelerate growth.",
  email: "hello@solyio.com",
  phone: "+1-678-551-7478",
  twitter: "@solyio",
  foundingDate: "2024",
  logo: "/logo.svg",
  /** Social cards are generated by app/opengraph-image.tsx, not a static file. */
  ogImage: "/opengraph-image",
} as const

export function absoluteUrl(path = "/"): string {
  if (path.startsWith("http")) return path
  return `${SITE.url}${path.startsWith("/") ? path : `/${path}`}`
}

/**
 * Next merges `metadata.openGraph` SHALLOWLY — a page that declares the object
 * at all replaces the root layout's entirely, silently dropping og:image.
 * Spread this into every page-level openGraph block so the card never breaks.
 *
 * Images are generated at build time by the `opengraph-image` file convention,
 * so there is no static asset to go missing.
 */
export function ogImage(path = "/opengraph-image", alt = `${SITE.name} — ${SITE.tagline}`) {
  return [{ url: path, width: 1200, height: 630, alt, type: "image/png" }]
}

/* ─── Route registry ─────────────────────────────────────────────── */

type ChangeFreq = "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never"

export interface RouteEntry {
  path: string
  changeFrequency: ChangeFreq
  priority: number
}

/** Marketing + conversion pages. */
export const CORE_ROUTES: RouteEntry[] = [
  { path: "/", changeFrequency: "weekly", priority: 1.0 },
  { path: "/services", changeFrequency: "monthly", priority: 0.9 },
  { path: "/portfolio", changeFrequency: "weekly", priority: 0.9 },
  { path: "/book", changeFrequency: "monthly", priority: 0.9 },
  { path: "/pricing", changeFrequency: "monthly", priority: 0.9 },
  { path: "/industries", changeFrequency: "monthly", priority: 0.8 },
  { path: "/products", changeFrequency: "monthly", priority: 0.8 },
  { path: "/about", changeFrequency: "monthly", priority: 0.7 },
  { path: "/contact", changeFrequency: "monthly", priority: 0.8 },
  { path: "/careers", changeFrequency: "monthly", priority: 0.5 },
]

/** One page per service — the highest commercial-intent cluster on the site. */
export const SERVICE_ROUTES: RouteEntry[] = [
  { path: "/services/ai-automation", changeFrequency: "monthly", priority: 0.9 },
  { path: "/services/web-development", changeFrequency: "monthly", priority: 0.9 },
  { path: "/services/mobile-development", changeFrequency: "monthly", priority: 0.9 },
  { path: "/services/cloud-infrastructure", changeFrequency: "monthly", priority: 0.9 },
  { path: "/services/cyber-security", changeFrequency: "monthly", priority: 0.9 },
  { path: "/services/marketing-services", changeFrequency: "monthly", priority: 0.9 },
]

export const LEGAL_ROUTES: RouteEntry[] = [
  { path: "/privacy-policy", changeFrequency: "yearly", priority: 0.3 },
  { path: "/terms-of-service", changeFrequency: "yearly", priority: 0.3 },
  { path: "/refund-policy", changeFrequency: "yearly", priority: 0.3 },
]

/* ─── Structured data ────────────────────────────────────────────── */

export const ORGANIZATION_ID = `${SITE.url}/#organization`
export const WEBSITE_ID = `${SITE.url}/#website`

export const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": ORGANIZATION_ID,
  name: SITE.name,
  url: SITE.url,
  logo: {
    "@type": "ImageObject",
    url: absoluteUrl(SITE.logo),
  },
  description: SITE.description,
  foundingDate: SITE.foundingDate,
  slogan: SITE.tagline,
  knowsAbout: [
    "Web Development",
    "Mobile App Development",
    "Cloud Infrastructure",
    "AI Automation",
    "AI Agents",
    "Cyber Security",
    "SaaS Product Engineering",
  ],
  sameAs: [
    "https://twitter.com/solyio",
    "https://linkedin.com/company/solyio",
    "https://github.com/solyio",
  ],
  contactPoint: [
    {
      "@type": "ContactPoint",
      telephone: SITE.phone,
      contactType: "sales",
      email: SITE.email,
      availableLanguage: ["English"],
      areaServed: ["US", "GB", "DE", "FR", "NL", "ES", "IT", "CA", "AU"],
    },
  ],
  areaServed: [
    { "@type": "Country", name: "United States" },
    { "@type": "Country", name: "United Kingdom" },
    { "@type": "Country", name: "Germany" },
    { "@type": "Country", name: "France" },
    { "@type": "Country", name: "Netherlands" },
  ],
}

export const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": WEBSITE_ID,
  url: SITE.url,
  name: SITE.name,
  description: SITE.description,
  inLanguage: "en",
  publisher: { "@id": ORGANIZATION_ID },
}

export interface Crumb {
  name: string
  path: string
}

/** BreadcrumbList for a specific page. Always lead with Home. */
export function breadcrumbSchema(crumbs: Crumb[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [{ name: "Home", path: "/" }, ...crumbs].map((c, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: c.name,
      item: absoluteUrl(c.path),
    })),
  }
}

export interface Faq {
  q: string
  a: string
}

/** FAQPage — only ever emit this on a page whose visible content shows these Q&As. */
export function faqSchema(faqs: Faq[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  }
}

export function serviceSchema(opts: {
  name: string
  serviceType: string
  description: string
  path: string
  offers?: { name: string; description: string }[]
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    "@id": `${absoluteUrl(opts.path)}#service`,
    name: opts.name,
    serviceType: opts.serviceType,
    description: opts.description,
    url: absoluteUrl(opts.path),
    provider: { "@id": ORGANIZATION_ID },
    areaServed: "Worldwide",
    ...(opts.offers?.length
      ? {
          hasOfferCatalog: {
            "@type": "OfferCatalog",
            name: `${opts.name} Packages`,
            itemListElement: opts.offers.map((o) => ({
              "@type": "Offer",
              itemOffered: { "@type": "Service", name: o.name, description: o.description },
            })),
          },
        }
      : {}),
  }
}
