import Link from "next/link"
import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { SiteNavbar } from "@/components/site-navbar"
import { SiteFooter } from "@/components/site-footer"
import { JsonLd } from "@/components/json-ld"
import { BlockRenderer } from "@/components/blog/blocks"
import { TableOfContents } from "@/components/blog/table-of-contents"
import { PostCard } from "@/components/blog/post-card"
import { Inline } from "@/components/blog/inline"
import {
  formatPostDate,
  getAllFaqs,
  getAllPosts,
  getAuthor,
  getCategory,
  getPostBySlug,
  getReadingMinutes,
  getRelatedPosts,
  getToc,
  getWordCount,
  stripInline,
} from "@/lib/blog"
import { ORGANIZATION_ID, SITE, absoluteUrl, breadcrumbSchema, faqSchema, ogImage } from "@/lib/seo"

export function generateStaticParams() {
  return getAllPosts().map((p) => ({ slug: p.slug }))
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const post = getPostBySlug(slug)
  if (!post) return { title: "Post not found" }

  const url = absoluteUrl(`/blog/${post.slug}`)
  const author = getAuthor(post.author)

  return {
    title: post.seoTitle ?? post.title,
    description: post.description,
    keywords: [post.primaryKeyword, ...post.tags],
    authors: [{ name: author.name, url: author.url }],
    alternates: { canonical: url },
    openGraph: {
      type: "article",
      url,
      title: post.seoTitle ?? post.title,
      description: post.description,
      siteName: SITE.name,
      publishedTime: post.publishedAt,
      modifiedTime: post.updatedAt ?? post.publishedAt,
      authors: [author.name],
      tags: post.tags,
      // Per-post card generated by app/blog/[slug]/opengraph-image.tsx.
      images: post.cover
        ? [{ url: post.cover, alt: post.title }]
        : ogImage(`/blog/${post.slug}/opengraph-image`, post.title),
    },
    twitter: {
      card: "summary_large_image",
      title: post.seoTitle ?? post.title,
      description: post.description,
      images: post.cover ? [post.cover] : [`/blog/${post.slug}/opengraph-image`],
    },
  }
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const post = getPostBySlug(slug)
  if (!post) notFound()

  const author = getAuthor(post.author)
  const category = getCategory(post.category)
  const toc = getToc(post)
  const related = getRelatedPosts(post, 3)
  const minutes = getReadingMinutes(post)
  const faqs = getAllFaqs(post)
  const url = absoluteUrl(`/blog/${post.slug}`)

  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    "@id": `${url}#article`,
    headline: stripInline(post.title),
    description: post.description,
    articleSection: category?.name,
    keywords: [post.primaryKeyword, ...post.tags].join(", "),
    wordCount: getWordCount(post),
    inLanguage: "en",
    url,
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    datePublished: post.publishedAt,
    dateModified: post.updatedAt ?? post.publishedAt,
    author: {
      "@type": "Organization",
      name: author.name,
      url: author.url,
      description: author.bio,
      ...(author.sameAs ? { sameAs: author.sameAs } : {}),
    },
    publisher: { "@id": ORGANIZATION_ID },
    isPartOf: { "@id": `${absoluteUrl("/blog")}#blog` },
    ...(post.cover ? { image: absoluteUrl(post.cover) } : {}),
  }

  const crumbs = breadcrumbSchema([
    { name: "Blog", path: "/blog" },
    ...(category ? [{ name: category.name, path: `/blog/category/${category.slug}` }] : []),
    { name: stripInline(post.title), path: `/blog/${post.slug}` },
  ])

  const schemas: object[] = [articleSchema, crumbs]
  if (faqs.length) schemas.push(faqSchema(faqs))

  return (
    <div className="font-body min-h-screen bg-[#fcf9f8] text-[#1c1b1b] antialiased">
      <JsonLd data={schemas} />
      <SiteNavbar />

      <main>
        {/* ── HEADER ───────────────────────────────────────────── */}
        <header className="relative overflow-hidden px-6 pt-32 pb-12 md:px-10 md:pt-40">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute -top-40 right-10 h-[420px] w-[420px] rounded-full bg-[#FF1E41]/5 blur-[130px]" />
          </div>

          <div className="relative z-10 mx-auto max-w-3xl">
            {/* Visible breadcrumb — matches the BreadcrumbList schema above. */}
            <nav aria-label="Breadcrumb" className="mb-8">
              <ol className="flex flex-wrap items-center gap-2 text-[11px] font-bold uppercase tracking-[0.15em] text-[#5e3f3e]/50">
                <li>
                  <Link href="/blog" className="transition-colors hover:text-[#bb0029]">
                    Blog
                  </Link>
                </li>
                {category && (
                  <>
                    <li aria-hidden="true">/</li>
                    <li>
                      <Link
                        href={`/blog/category/${category.slug}`}
                        className="transition-colors hover:text-[#bb0029]"
                      >
                        {category.name}
                      </Link>
                    </li>
                  </>
                )}
              </ol>
            </nav>

            {post.eyebrow && (
              <div className="font-headline mb-5 text-[10px] font-bold uppercase tracking-[0.3em] text-[#FF1E41]">
                {post.eyebrow}
              </div>
            )}

            <h1 className="font-headline mb-6 text-4xl font-bold leading-[1.05] tracking-tighter text-[#1c1b1b] md:text-6xl">
              {post.title}
            </h1>

            <p className="mb-8 text-xl font-light leading-relaxed text-[#534342]">{post.description}</p>

            <div className="flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-[#d8c2c1]/40 pt-6 text-sm text-[#5e3f3e]/70">
              <span className="font-semibold text-[#1c1b1b]">{author.name}</span>
              <span aria-hidden="true" className="text-[#d8c2c1]">
                ·
              </span>
              <time dateTime={post.publishedAt}>{formatPostDate(post.publishedAt)}</time>
              {post.updatedAt && post.updatedAt !== post.publishedAt && (
                <>
                  <span aria-hidden="true" className="text-[#d8c2c1]">
                    ·
                  </span>
                  <span>Updated {formatPostDate(post.updatedAt)}</span>
                </>
              )}
              <span aria-hidden="true" className="text-[#d8c2c1]">
                ·
              </span>
              <span>{minutes} min read</span>
            </div>
          </div>
        </header>

        {/* ── BODY ─────────────────────────────────────────────── */}
        <div className="px-6 pb-24 md:px-10">
          <div className="mx-auto grid max-w-screen-xl gap-12 lg:grid-cols-12">
            {/* Sidebar TOC */}
            <aside className="hidden lg:col-span-3 lg:block">
              <div className="sticky top-28">
                <TableOfContents entries={toc} />
              </div>
            </aside>

            <article className="min-w-0 lg:col-span-9 xl:col-span-6">
              {/* Key takeaways — the direct answer, stated before the long read.
                  This is the block AI search engines lift and cite. */}
              {post.keyTakeaways.length > 0 && (
                <div className="mb-12 rounded-3xl border border-[#1c1b1b]/10 bg-white p-7 md:p-8">
                  <h2 className="font-headline mb-5 text-[10px] font-bold uppercase tracking-[0.3em] text-[#FF1E41]">
                    The short answer
                  </h2>
                  <ul className="space-y-3.5">
                    {post.keyTakeaways.map((t, i) => (
                      <li key={i} className="flex gap-3 text-[16px] leading-[1.65] text-[#1c1b1b]">
                        <span
                          className="material-symbols-outlined mt-0.5 shrink-0 text-[#FF1E41]"
                          style={{ fontSize: "18px" }}
                        >
                          check_circle
                        </span>
                        <span>
                          <Inline text={t} />
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {post.blocks.map((block, i) => (
                <BlockRenderer key={i} block={block} />
              ))}

              {/* FAQ */}
              {post.faqs && post.faqs.length > 0 && (
                <section className="mt-16">
                  <h2
                    id="faq"
                    className="font-headline scroll-mt-28 mb-6 text-3xl font-bold tracking-tight text-[#1c1b1b] md:text-4xl"
                  >
                    Frequently asked questions
                  </h2>
                  <BlockRenderer block={{ type: "faq", items: post.faqs }} />
                </section>
              )}

              {/* Tags */}
              {post.tags.length > 0 && (
                <div className="mt-14 flex flex-wrap gap-2 border-t border-[#d8c2c1]/40 pt-8">
                  {post.tags.map((t) => (
                    <span
                      key={t}
                      className="rounded-full bg-[#f0eded] px-3 py-1.5 text-[11px] font-medium text-[#5e3f3e]"
                    >
                      {t}
                    </span>
                  ))}
                </div>
              )}

              {/* Author */}
              <div className="mt-10 flex gap-5 rounded-3xl border border-[#d8c2c1]/40 bg-white p-7">
                <div className="font-headline kinetic-gradient flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl text-lg font-black text-white">
                  S
                </div>
                <div className="min-w-0">
                  <div className="font-headline text-lg font-bold tracking-tight text-[#1c1b1b]">
                    {author.name}
                  </div>
                  <div className="mb-3 text-[11px] font-bold uppercase tracking-[0.15em] text-[#FF1E41]">
                    {author.role}
                  </div>
                  <p className="text-[15px] leading-relaxed text-[#5e3f3e]/85">{author.bio}</p>
                </div>
              </div>
            </article>

            {/* Right rail CTA */}
            <aside className="hidden xl:col-span-3 xl:block">
              <div className="sticky top-28 rounded-3xl bg-[#0f0e0e] p-7">
                <div className="font-headline mb-3 text-[10px] font-bold uppercase tracking-[0.3em] text-[#FF1E41]">
                  Working on this?
                </div>
                <p className="mb-6 text-[15px] leading-relaxed text-white/65">
                  We scope and quote projects like the one described here every week. Fixed price,
                  before any work starts.
                </p>
                <Link
                  href="/book"
                  className="font-headline block rounded-full bg-[#FF1E41] px-5 py-3 text-center text-[11px] font-bold uppercase tracking-widest text-white transition-all hover:bg-[#bb0029] active:scale-95"
                >
                  Book a free call
                </Link>
                <Link
                  href="/pricing"
                  className="font-headline mt-3 block rounded-full border border-white/15 px-5 py-3 text-center text-[11px] font-bold uppercase tracking-widest text-white/70 transition-all hover:border-white/30 hover:text-white"
                >
                  See pricing
                </Link>
              </div>
            </aside>
          </div>
        </div>

        {/* ── RELATED ──────────────────────────────────────────── */}
        {related.length > 0 && (
          <section className="border-t border-[#d8c2c1]/30 px-6 py-20 md:px-10">
            <div className="mx-auto max-w-screen-xl">
              <h2 className="font-headline mb-8 text-2xl font-bold tracking-tight text-[#1c1b1b] md:text-3xl">
                Keep reading
              </h2>
              <div className="grid gap-6 md:grid-cols-3">
                {related.map((p) => (
                  <PostCard key={p.slug} post={p} />
                ))}
              </div>
            </div>
          </section>
        )}
      </main>

      <SiteFooter />
    </div>
  )
}
